# Autogenerated wrapper script for FXdiv_jll for any
export fxdiv_h

JLLWrappers.@generate_wrapper_header("FXdiv")
JLLWrappers.@declare_file_product(fxdiv_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        fxdiv_h,
        "include/fxdiv.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
